### ISSUE TITLE
where is setur10?

### ISSUE THREAD

**Issue by piaopiaojie** [zhongjieGDUT/manipulation_planning_Matlab#1]
hello,
        Very appreciated of your code of rrt,Can you please show the data of setur10? 
        Thank you.

**Comment by zhongjieGDUT** [comment]
now it is there

**Comment by zhongjieGDUT** [comment]
> hello,
> Very appreciated of your code of rrt,Can you please show the data of setur10?
> Thank you.
 you need the 3D data of ur10 from http://arvc.umh.es/arte/index_en.html

**Comment by JNURay** [comment]
你好，谢谢分享代码，请问为什么在运行setur10的时候，出现se2t报错，这个是什么呀

**Comment by zhongjieGDUT** [comment]
> 你好，谢谢分享代码，请问为什么在运行setur10的时候，出现se2t报错，这个是什么呀



> 你好，谢谢分享代码，请问为什么在运行setur10的时候，出现se2t报错，这个是什么呀

**Comment by zhongjieGDUT** [comment]
> 你好，谢谢分享代码，请问为什么在运行setur10的时候，出现se2t报错，这个是什么呀

这个是把SE(3)位姿数据转成一个4*4矩阵，我看了下这个代码，由于本身工具箱的问题，很多bug我忘记怎么改了，建议使用matlab2019b的机器人系统工具箱，比这个第三方的强大太多。
